apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecampus-notification
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: https://github.com/worryyy/app-test.git
    targetRevision: main
    path: k3s/charts/go-service
    helm:
      releaseName: ecampus-notification
      valueFiles:
        - ../../helm-values/workloads/ecampus-notification.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
