replicaCount: 1

image:
  registry: crpi-gfwwpdquc14b7w22.cn-shanghai.personal.cr.aliyuncs.com
  repository: pulseops/go-service
  tag: dev
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets:
    - tcr-secret

nameOverride: ""
fullnameOverride: ""

app:
  port: 8080
  profile: dev

platform:
  serviceName: ""

release:
  deployId: ""
  releaseBatch: ""
  gitSha: ""
  gitopsRevision: ""
  environment: dev
  buildNumber: ""

service:
  type: ClusterIP
  port: 80

observability:
  releaseInfo:
    enabled: false
    path: /metrics
    port: ""

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /
  paths: []
  pathType: Prefix
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: null

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
