apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecampus-release
  namespace: delivery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecampus-release
  namespace: app
rules:
  - apiGroups: [apps]
    resources: [deployments, deployments/status, replicasets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods, services, endpoints]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecampus-release
  namespace: app
subjects:
  - kind: ServiceAccount
    name: ecampus-release
    namespace: delivery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecampus-release
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecampus-release
  namespace: argocd
rules:
  - apiGroups: [argoproj.io]
    resources: [applications, applications/status]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecampus-release
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: ecampus-release
    namespace: delivery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecampus-release
