apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-addons
  namespace: argocd
spec:
  description: Platform controllers and observability addons

  sourceRepos:
    - '*'

  destinations:
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
