{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goService.ingressName" . }}
  labels:
    {{- include "goService.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          {{- $paths := .Values.ingress.paths }}
          {{- if not $paths }}
          {{- $paths = list .Values.ingress.path }}
          {{- end }}
          {{- range $path := $paths }}
          - path: {{ $path | quote }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "goService.fullname" $ }}
                port:
                  name: http
          {{- end }}
{{- end }}
