apiVersion: v1
kind: Service
metadata:
  name: {{ include "goService.stableServiceName" . }}
  labels:
    {{- include "goService.labels" . | nindent 4 }}
    rollouts.argoproj.io/service-role: stable
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "goService.selectorLabels" . | nindent 4 }}
{{- if eq (include "goService.rolloutEnabled" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goService.candidateServiceName" . }}
  labels:
    {{- include "goService.labels" . | nindent 4 }}
    rollouts.argoproj.io/service-role: canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "goService.selectorLabels" . | nindent 4 }}
{{- end }}
