#!/usr/bin/env sh
# Regenerate k3s/helm-values/platform/grafana-dashboards.yaml (the generated
# chart values block) from the dashboard sources in monitoring/dashboards/.
# Run after editing any *.json there; commit both together.
set -eu

repo_root=$(git rev-parse --show-toplevel)
src_dir="${repo_root}/monitoring/dashboards"
out_file="${repo_root}/k3s/helm-values/platform/grafana-dashboards.yaml"

python3 - "$src_dir" "$out_file" <<'PY'
import json
import sys
from pathlib import Path

src_dir, out_file = Path(sys.argv[1]), Path(sys.argv[2])

dashboards = {}
for path in sorted(src_dir.glob("*.json")):
    board = json.loads(path.read_text())
    uid = board.get("uid")
    if not uid:
        raise SystemExit(f"{path}: dashboard json needs a top-level uid")
    dashboards[uid] = json.dumps(board, ensure_ascii=False)

if not dashboards:
    raise SystemExit("no dashboards found in monitoring/dashboards")

lines = [
    "# GENERATED by k3s/ci/scripts/sync-dashboards.sh — do not edit by hand.\n",
    "# Source of truth: monitoring/dashboards/*.json (see that README for the\n",
    "# uid -> dashboard mapping).\n",
    "\n",
    "dashboardProviders:\n",
    "  dashboardproviders.yaml:\n",
    "    apiVersion: 1\n",
    "    providers:\n",
    "      - name: default\n",
    "        orgId: 1\n",
    "        folder: \"\"\n",
    "        type: file\n",
    "        disableDeletion: false\n",
    "        updateIntervalSeconds: 30\n",
    "        options:\n",
    "          path: /var/lib/grafana/dashboards/default\n",
    "\n",
    "dashboards:\n",
    "  default:\n",
]
for uid, payload in dashboards.items():
    lines.append(f"    {uid}:\n")
    lines.append(f"      json: |-{chr(10)}        {payload}{chr(10)}")

out_file.write_text("".join(lines))
print(f"wrote {out_file} with {len(dashboards)} dashboards: {', '.join(dashboards)}")
PY
