apiVersion: v1
kind: Secret
metadata:
  name: platform-postgresql-auth
  namespace: delivery
type: Opaque
stringData:
  postgres-password: "change-me-superuser"
  password: "change-me-platform"
  username: "platform_user"
  # postgres://platform_user:change-me-platform@platform-postgresql-postgresql.delivery.svc:5432/platform_db?sslmode=disable
  database-url: "postgres://platform_user:change-me-platform@platform-postgresql-postgresql.delivery.svc:5432/platform_db?sslmode=disable"
