apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: platform-addons

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: 2.41.0
      helm:
        releaseName: argo-rollouts
        valueFiles:
          - $values/k3s/helm-values/platform/argo-rollouts.yaml
    - repoURL: https://github.com/worryyy/devops-test.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
